mv data/split/AGTCAA_RA_GGACAAGCTATGCAG.fastq data/renamed/WS_DC01_RA.fastq
mv data/split/AGTCAA_RA_GGAACAACCATGCAG.fastq data/renamed/WS_DC02_RA.fastq
mv data/split/AGTCAA_RA_GGAGATCGCATGCAG.fastq data/renamed/WS_DC03_RA.fastq
mv data/split/AGTCAA_RA_GGCCGAAGTATGCAG.fastq data/renamed/WS_DC04_RA.fastq
mv data/split/AGTCAA_RA_GGGATAGACATGCAG.fastq data/renamed/WS_DC05_RA.fastq
mv data/split/AGTCAA_RA_GGTATCAGCATGCAG.fastq data/renamed/WS_DC06_RA.fastq
mv data/split/AGTCAA_RA_GGAATGTTGCTGCAG.fastq data/renamed/WS_DC07_RA.fastq
mv data/split/AGTCAA_RA_GGCCATCCTCTGCAG.fastq data/renamed/WS_DC08_RA.fastq
mv data/split/AGTCAA_RA_GGAAACATCGTGCAG.fastq data/renamed/WS_DC09_RA.fastq
mv data/split/AGTCAA_RA_GGAACCGAGATGCAG.fastq data/renamed/WS_DC10_RA.fastq
mv data/split/AGTCAA_RA_GGAGCAGGAATGCAG.fastq data/renamed/WS_DC11_RA.fastq
mv data/split/AGTCAA_RA_GGCCGTGAGATGCAG.fastq data/renamed/WS_DC12_RA.fastq
mv data/split/AGTCAA_RA_GGGCCACATATGCAG.fastq data/renamed/WS_DC13_RA.fastq
mv data/split/AGTCAA_RA_GGTCCGTCTATGCAG.fastq data/renamed/WS_DC14_RA.fastq
mv data/split/AGTCAA_RA_GGACACTGACTGCAG.fastq data/renamed/WS_DC15_RA.fastq
mv data/split/AGTCAA_RA_GGCCGACAACTGCAG.fastq data/renamed/WS_TMC01_RA.fastq
mv data/split/AGTCAA_RA_GGACATTGGCTGCAG.fastq data/renamed/WS_TMC02_RA.fastq
mv data/split/AGTCAA_RA_GGAACGCTTATGCAG.fastq data/renamed/WS_TMC03_RA.fastq
mv data/split/AGTCAA_RA_GGAGTCACTATGCAG.fastq data/renamed/WS_TMC04_RA.fastq
mv data/split/AGTCAA_RA_GGCCTCCTGATGCAG.fastq data/renamed/WS_TMC05_RA.fastq
mv data/split/AGTCAA_RA_GGGCGAGTAATGCAG.fastq data/renamed/WS_TMC06_RA.fastq
mv data/split/AGTCAA_RA_GGTCTTCACATGCAG.fastq data/renamed/WS_TMC07_RA.fastq
mv data/split/AGTCAA_RA_GGACAGATTCTGCAG.fastq data/renamed/WS_TMC08_RA.fastq
mv data/split/AGTCAA_RA_GGAGTCAAGCTGCAG.fastq data/renamed/WS_TMC09_RA.fastq
mv data/split/AGTCAA_RA_GGACCACTGTTGCAG.fastq data/renamed/WS_TMC10_RA.fastq
mv data/split/AGTCAA_RA_GGAAGACGGATGCAG.fastq data/renamed/WS_TMC11_RA.fastq
mv data/split/AGTCAA_RA_GGATCCTGTATGCAG.fastq data/renamed/WS_TMC12_RA.fastq
mv data/split/AGTCAA_RA_GGCGAACTTATGCAG.fastq data/renamed/WS_TMC13_RA.fastq
mv data/split/AGTCAA_RA_GGGCTAACGATGCAG.fastq data/renamed/WS_TMC14_RA.fastq
mv data/split/AGTCAA_RA_GGTGAAGAGATGCAG.fastq data/renamed/WS_HC1_RA.fastq
mv data/split/AGTCAA_RA_GGAGATGTACTGCAG.fastq data/renamed/WS_TMC15_RA.fastq
mv data/split/AGTCAA_RA_GGCCTCTATCTGCAG.fastq data/renamed/WS_HC2_RA.fastq
mv data/split/AGTCAA_RA_GGAACGTGATTGCAG.fastq data/renamed/WS_HC3_RA.fastq
mv data/split/AGTCAA_RA_GGAAGGTACATGCAG.fastq data/renamed/WS_HC4_RA.fastq
mv data/split/AGTCAA_RA_GGATTGAGGATGCAG.fastq data/renamed/WS_HC5_RA.fastq
mv data/split/AGTCAA_RA_GGCGACTGGATGCAG.fastq data/renamed/WS_HC6_RA.fastq
mv data/split/AGTCAA_RA_GGGCTCGGTATGCAG.fastq data/renamed/WS_HC7_RA.fastq
mv data/split/AGTCAA_RA_GGTGGAACAATGCAG.fastq data/renamed/WS_HC8_RA.fastq
mv data/split/AGTCAA_RA_GGAGCACCTCTGCAG.fastq data/renamed/WCS_01_RA.fastq
mv data/split/AGTCAA_RA_GGCGACACACTGCAG.fastq data/renamed/WCS_02_RA.fastq
mv data/split/AGTCAA_RA_GGCGCTGATCTGCAG.fastq data/renamed/WCS_03_RA.fastq
mv data/split/AGTCAA_RA_GGACACAGAATGCAG.fastq data/renamed/WCS_04_RA.fastq
mv data/split/AGTCAA_RA_GGCAACCACATGCAG.fastq data/renamed/WCS_05_RA.fastq
mv data/split/AGTCAA_RA_GGCGCATACATGCAG.fastq data/renamed/WCS_06_RA.fastq
mv data/split/AGTCAA_RA_GGGGAGAACATGCAG.fastq data/renamed/WCS_07_RA.fastq
mv data/split/AGTCAA_RA_GGTGGCTTCATGCAG.fastq data/renamed/WCS_08_RA.fastq
mv data/split/AGTCAA_RA_GGAGCCATGCTGCAG.fastq data/renamed/WCS_09_RA.fastq
mv data/split/AGTCAA_RA_GGCGGATTGCTGCAG.fastq data/renamed/WCS_10_RA.fastq
mv data/split/AGTCAA_RA_GGCAGATCTGTGCAG.fastq data/renamed/WCS_11_RA.fastq
mv data/split/AGTCAA_RA_GGACAGCAGATGCAG.fastq data/renamed/WCS_12_RA.fastq
mv data/split/AGTCAA_RA_GGCAAGACTATGCAG.fastq data/renamed/WCS_13_RA.fastq
mv data/split/AGTCAA_RA_GGCTCAATGATGCAG.fastq data/renamed/WCS_14_RA.fastq
mv data/split/AGTCAA_RA_GGGGTGCGAATGCAG.fastq data/renamed/WCS_15_RA.fastq
mv data/split/AGTCAA_RA_GGTGGTGGTATGCAG.fastq data/renamed/WCS_16_RA.fastq
mv data/split/AGTCAA_RA_GGAGGCTAACTGCAG.fastq data/renamed/WCS_17_RA.fastq
mv data/split/AGTCAA_RA_GGCTAAGGTCTGCAG.fastq data/renamed/WCS_18_RA.fastq
mv data/split/AGTCAA_RA_GGATGCCTAATGCAG.fastq data/renamed/WCS_19_RA.fastq
mv data/split/AGTCAA_RA_GGACCTCCAATGCAG.fastq data/renamed/WCS_20_RA.fastq
mv data/split/AGTCAA_RA_GGCAATGGAATGCAG.fastq data/renamed/WCS_21_RA.fastq
mv data/split/AGTCAA_RA_GGCTGAGCCATGCAG.fastq data/renamed/WCS_22_RA.fastq
mv data/split/AGTCAA_RA_GGGTACGCAATGCAG.fastq data/renamed/WCS_23_RA.fastq
mv data/split/AGTCAA_RA_GGTTCACGCATGCAG.fastq data/renamed/WCS_24_RA.fastq
mv data/split/AGTCAA_RA_GGATAGCGACTGCAG.fastq data/renamed/WCS_25_RA.fastq
mv data/split/AGTCAA_RA_GGGAACAGGCTGCAG.fastq data/renamed/WCS_26_RA.fastq
mv data/split/AGTCAA_RA_GGAACGAACGTGCAG.fastq data/renamed/WCS_27_RA.fastq
mv data/split/AGTCAA_RA_GGACGCTCGATGCAG.fastq data/renamed/S_TR_01_RA.fastq
mv data/split/AGTCAA_RA_GGCACTTCGATGCAG.fastq data/renamed/S_TR_02_RA.fastq
mv data/split/AGTCAA_RA_GGCTGGCATATGCAG.fastq data/renamed/S_TR_03_RA.fastq
mv data/split/AGTCAA_RA_GGGTCGTAGATGCAG.fastq data/renamed/S_TR_04_RA.fastq
mv data/split/AGTCAA_RA_GGACACGAGATGCAG.fastq data/renamed/S_TR_05_RA.fastq
mv data/split/AGTCAA_RA_GGACGACAAGTGCAG.fastq data/renamed/S_TR_06_RA.fastq
mv data/split/AGTCAA_RA_GGGACAGTGCTGCAG.fastq data/renamed/S_TR_07_RA.fastq
mv data/split/AGTCAA_RA_GGAGTACAAGTGCAG.fastq data/renamed/S_TR_08_RA.fastq
mv data/split/AGTCAA_RA_GGACGTATCATGCAG.fastq data/renamed/S_TR_09_RA.fastq
mv data/split/AGTCAA_RA_GGCAGCGTTATGCAG.fastq data/renamed/S_TR_10_RA.fastq
mv data/split/AGTCAA_RA_GGGAATCTGATGCAG.fastq data/renamed/S_TR_11_RA.fastq
mv data/split/AGTCAA_RA_GGGTCTGTCATGCAG.fastq data/renamed/S_TR_12_RA.fastq
mv data/split/AGTCAA_RA_GGAAGAGATCTGCAG.fastq data/renamed/S_TR_13_RA.fastq
mv data/split/AGTCAA_RA_GGATTGGCTCTGCAG.fastq data/renamed/S_TR_14_RA.fastq
mv data/split/AGTCAA_RA_GGGAGTTAGCTGCAG.fastq data/renamed/S_TR_15_RA.fastq
mv data/split/AGTCAA_RA_GGCATCAAGTTGCAG.fastq data/renamed/S_TR_16_RA.fastq
mv data/split/AGTCAA_RA_GGACTATGCATGCAG.fastq data/renamed/S_TR_17_RA.fastq
mv data/split/AGTCAA_RA_GGCATACCAATGCAG.fastq data/renamed/S_TR_18_RA.fastq
mv data/split/AGTCAA_RA_GGGACTAGTATGCAG.fastq data/renamed/S_TR_19_RA.fastq
mv data/split/AGTCAA_RA_GGGTGTTCTATGCAG.fastq data/renamed/S_TR_20_RA.fastq
mv data/split/AGTCAA_RA_GGAAGGACACTGCAG.fastq data/renamed/TS_EFCR_01_RA.fastq
mv data/split/AGTCAA_RA_GGCAAGGAGCTGCAG.fastq data/renamed/TS_EFCR_02_RA.fastq
mv data/split/AGTCAA_RA_GGGATGAATCTGCAG.fastq data/renamed/TS_EFCR_03_RA.fastq
mv data/split/AGTCAA_RA_GGAGTGGTCATGCAG.fastq data/renamed/TS_EFCR_04_RA.fastq
mv data/split/AGTCAA_RA_GGAGAGTCAATGCAG.fastq data/renamed/TS_EFCR_05_RA.fastq
mv data/split/AGTCAA_RA_GGCCAGTTCATGCAG.fastq data/renamed/TS_EFCR_06_RA.fastq
mv data/split/AGTCAA_RA_GGGAGCTGAATGCAG.fastq data/renamed/TS_EFCR_07_RA.fastq
mv data/split/AGTCAA_RA_GGTAGGATGATGCAG.fastq data/renamed/TS_EFCR_08_RA.fastq
mv data/split/AGTCAA_RA_GGAATCCGTCTGCAG.fastq data/renamed/TS_EFCR_09_RA.fastq
mv data/split/AGTCAA_RA_GGCACCTTACTGCAG.fastq data/renamed/TS_EFCR_10_RA.fastq
mv data/split/AGTCAA_RA_GGGCCAAGACTGCAG.fastq data/renamed/TS_EFCR_11_RA.fastq
mv data/split/GTCCGC_RA_GGACAAGCTATGCAG.fastq data/renamed/TS_EFCR_12_RA.fastq
mv data/split/GTCCGC_RA_GGAACAACCATGCAG.fastq data/renamed/TS_EFCR_13_RA.fastq
mv data/split/GTCCGC_RA_GGAGATCGCATGCAG.fastq data/renamed/TS_EFCR_14_RA.fastq
mv data/split/GTCCGC_RA_GGCCGAAGTATGCAG.fastq data/renamed/TS_EFCR_15_RA.fastq
mv data/split/GTCCGC_RA_GGGATAGACATGCAG.fastq data/renamed/TS_EFCR_16_RA.fastq
mv data/split/GTCCGC_RA_GGTATCAGCATGCAG.fastq data/renamed/TS_EFCR_17_RA.fastq
mv data/split/GTCCGC_RA_GGAATGTTGCTGCAG.fastq data/renamed/TS_EFCR_18_RA.fastq
mv data/split/GTCCGC_RA_GGCCATCCTCTGCAG.fastq data/renamed/TS_EFCR_19_RA.fastq
mv data/split/GTCCGC_RA_GGAAACATCGTGCAG.fastq data/renamed/934-002_RA.fastq
mv data/split/GTCCGC_RA_GGAACCGAGATGCAG.fastq data/renamed/934-003_RA.fastq
mv data/split/GTCCGC_RA_GGAGCAGGAATGCAG.fastq data/renamed/934-004_RA.fastq
mv data/split/GTCCGC_RA_GGCCGTGAGATGCAG.fastq data/renamed/934-005_RA.fastq
mv data/split/GTCCGC_RA_GGGCCACATATGCAG.fastq data/renamed/934-006_RA.fastq
mv data/split/GTCCGC_RA_GGTCCGTCTATGCAG.fastq data/renamed/934-007_RA.fastq
mv data/split/GTCCGC_RA_GGACACTGACTGCAG.fastq data/renamed/934-008_RA.fastq
mv data/split/GTCCGC_RA_GGCCGACAACTGCAG.fastq data/renamed/934-009_RA.fastq
mv data/split/GTCCGC_RA_GGACATTGGCTGCAG.fastq data/renamed/934-010_RA.fastq
mv data/split/GTCCGC_RA_GGAACGCTTATGCAG.fastq data/renamed/934-011_RA.fastq
mv data/split/GTCCGC_RA_GGAGTCACTATGCAG.fastq data/renamed/934-012_RA.fastq
mv data/split/GTCCGC_RA_GGCCTCCTGATGCAG.fastq data/renamed/934-013_RA.fastq
mv data/split/GTCCGC_RA_GGGCGAGTAATGCAG.fastq data/renamed/945-006_RA.fastq
mv data/split/GTCCGC_RA_GGTCTTCACATGCAG.fastq data/renamed/945-007_RA.fastq
mv data/split/GTCCGC_RA_GGACAGATTCTGCAG.fastq data/renamed/945-008_RA.fastq
mv data/split/GTCCGC_RA_GGAGTCAAGCTGCAG.fastq data/renamed/945-009_RA.fastq
mv data/split/GTCCGC_RA_GGACCACTGTTGCAG.fastq data/renamed/945-010_RA.fastq
mv data/split/GTCCGC_RA_GGAAGACGGATGCAG.fastq data/renamed/1208-008_RA.fastq
mv data/split/GTCCGC_RA_GGATCCTGTATGCAG.fastq data/renamed/1208-009_RA.fastq
mv data/split/GTCCGC_RA_GGCGAACTTATGCAG.fastq data/renamed/1208-010_RA.fastq
mv data/split/GTCCGC_RA_GGGCTAACGATGCAG.fastq data/renamed/1208-011_RA.fastq
mv data/split/GTCCGC_RA_GGTGAAGAGATGCAG.fastq data/renamed/1208-012_RA.fastq
mv data/split/GTCCGC_RA_GGAGATGTACTGCAG.fastq data/renamed/1208-013_RA.fastq
mv data/split/GTCCGC_RA_GGCCTCTATCTGCAG.fastq data/renamed/1208-014_RA.fastq
mv data/split/GTCCGC_RA_GGAACGTGATTGCAG.fastq data/renamed/1208-015_RA.fastq
mv data/split/GTCCGC_RA_GGAAGGTACATGCAG.fastq data/renamed/1208-016_RA.fastq
mv data/split/GTCCGC_RA_GGATTGAGGATGCAG.fastq data/renamed/1208-017_RA.fastq
mv data/split/GTCCGC_RA_GGCGACTGGATGCAG.fastq data/renamed/1208-058_RA.fastq
mv data/split/GTCCGC_RA_GGGCTCGGTATGCAG.fastq data/renamed/1208-059_RA.fastq
mv data/split/GTCCGC_RA_GGTGGAACAATGCAG.fastq data/renamed/1208-060_RA.fastq
mv data/split/GTCCGC_RA_GGAGCACCTCTGCAG.fastq data/renamed/1208-061_RA.fastq
mv data/split/GTCCGC_RA_GGCGACACACTGCAG.fastq data/renamed/1208-062_RA.fastq
mv data/split/GTCCGC_RA_GGCGCTGATCTGCAG.fastq data/renamed/1208-063_RA.fastq
mv data/split/GTCCGC_RA_GGACACAGAATGCAG.fastq data/renamed/1208-064_RA.fastq
mv data/split/GTCCGC_RA_GGCAACCACATGCAG.fastq data/renamed/1208-065_RA.fastq
mv data/split/GTCCGC_RA_GGCGCATACATGCAG.fastq data/renamed/1208-066_RA.fastq
mv data/split/GTCCGC_RA_GGGGAGAACATGCAG.fastq data/renamed/1208-067_RA.fastq
mv data/split/GTCCGC_RA_GGTGGCTTCATGCAG.fastq data/renamed/1272-011_RA.fastq
mv data/split/GTCCGC_RA_GGAGCCATGCTGCAG.fastq data/renamed/1272-012_RA.fastq
mv data/split/GTCCGC_RA_GGCGGATTGCTGCAG.fastq data/renamed/1272-013_RA.fastq
mv data/split/GTCCGC_RA_GGCAGATCTGTGCAG.fastq data/renamed/1272-014_RA.fastq
mv data/split/GTCCGC_RA_GGACAGCAGATGCAG.fastq data/renamed/1272-015_RA.fastq
mv data/split/GTCCGC_RA_GGCAAGACTATGCAG.fastq data/renamed/1272-016_RA.fastq
mv data/split/GTCCGC_RA_GGCTCAATGATGCAG.fastq data/renamed/1272-017_RA.fastq
mv data/split/GTCCGC_RA_GGGGTGCGAATGCAG.fastq data/renamed/1272-018_RA.fastq
mv data/split/GTCCGC_RA_GGTGGTGGTATGCAG.fastq data/renamed/1272-019_RA.fastq
mv data/split/GTCCGC_RA_GGAGGCTAACTGCAG.fastq data/renamed/1272-020_RA.fastq
mv data/split/GTCCGC_RA_GGCTAAGGTCTGCAG.fastq data/renamed/OSKR_1_RA.fastq
mv data/split/GTCCGC_RA_GGATGCCTAATGCAG.fastq data/renamed/OSKR_2_RA.fastq
mv data/split/GTCCGC_RA_GGACCTCCAATGCAG.fastq data/renamed/OSKR_3_RA.fastq
mv data/split/GTCCGC_RA_GGCAATGGAATGCAG.fastq data/renamed/OSKR_4_RA.fastq
mv data/split/GTCCGC_RA_GGCTGAGCCATGCAG.fastq data/renamed/OSKR_5_RA.fastq
mv data/split/GTCCGC_RA_GGGTACGCAATGCAG.fastq data/renamed/OSKR_6_RA.fastq
mv data/split/GTCCGC_RA_GGTTCACGCATGCAG.fastq data/renamed/OSKR_7_RA.fastq
mv data/split/GTCCGC_RA_GGATAGCGACTGCAG.fastq data/renamed/OSKR_8_RA.fastq
mv data/split/GTCCGC_RA_GGGAACAGGCTGCAG.fastq data/renamed/OSKR_9_RA.fastq
mv data/split/GTCCGC_RA_GGAACGAACGTGCAG.fastq data/renamed/OSKR_10_RA.fastq
mv data/split/GTCCGC_RA_GGACGCTCGATGCAG.fastq data/renamed/OSKR_11_RA.fastq
mv data/split/GTCCGC_RA_GGCACTTCGATGCAG.fastq data/renamed/OSKR_12_RA.fastq
mv data/split/GTCCGC_RA_GGCTGGCATATGCAG.fastq data/renamed/OSKR_13_RA.fastq
mv data/split/GTCCGC_RA_GGGTCGTAGATGCAG.fastq data/renamed/OSKR_14_RA.fastq
mv data/split/GTCCGC_RA_GGACACGAGATGCAG.fastq data/renamed/OSKR_15_RA.fastq
mv data/split/GTCCGC_RA_GGACGACAAGTGCAG.fastq data/renamed/OSKR_16_RA.fastq
mv data/split/GTCCGC_RA_GGGACAGTGCTGCAG.fastq data/renamed/OSKR_17_RA.fastq
mv data/split/GTCCGC_RA_GGAGTACAAGTGCAG.fastq data/renamed/OSKR_18_RA.fastq
mv data/split/GTCCGC_RA_GGACGTATCATGCAG.fastq data/renamed/OSKR_19_RA.fastq
mv data/split/GTCCGC_RA_GGCAGCGTTATGCAG.fastq data/renamed/OSKR_20_RA.fastq
mv data/split/GTCCGC_RA_GGGAATCTGATGCAG.fastq data/renamed/OSKR_21_RA.fastq
mv data/split/GTCCGC_RA_GGGTCTGTCATGCAG.fastq data/renamed/OSKR_22_RA.fastq
mv data/split/GTCCGC_RA_GGAAGAGATCTGCAG.fastq data/renamed/OSKR_23_RA.fastq
mv data/split/GTCCGC_RA_GGATTGGCTCTGCAG.fastq data/renamed/OSKR_24_RA.fastq
mv data/split/GTCCGC_RA_GGGAGTTAGCTGCAG.fastq data/renamed/OSKR_25_RA.fastq
mv data/split/GTCCGC_RA_GGCATCAAGTTGCAG.fastq data/renamed/OSKR_26_RA.fastq
mv data/split/GTCCGC_RA_GGACTATGCATGCAG.fastq data/renamed/OSKR_27_RA.fastq
mv data/split/GTCCGC_RA_GGCATACCAATGCAG.fastq data/renamed/OSKR_28_RA.fastq
mv data/split/GTCCGC_RA_GGGACTAGTATGCAG.fastq data/renamed/OSKR_29_RA.fastq
mv data/split/GTCCGC_RA_GGGTGTTCTATGCAG.fastq data/renamed/OSKR_30_RA.fastq
mv data/split/GTCCGC_RA_GGAAGGACACTGCAG.fastq data/renamed/OSKR_31_RA.fastq
mv data/split/GTCCGC_RA_GGCAAGGAGCTGCAG.fastq data/renamed/OSKR_32_RA.fastq
mv data/split/GTCCGC_RA_GGGATGAATCTGCAG.fastq data/renamed/OSKR_33_RA.fastq
mv data/split/GTCCGC_RA_GGAGTGGTCATGCAG.fastq data/renamed/OSKR_34_RA.fastq
mv data/split/GTCCGC_RA_GGAGAGTCAATGCAG.fastq data/renamed/OSKR_35_RA.fastq
mv data/split/GTCCGC_RA_GGCCAGTTCATGCAG.fastq data/renamed/OSKR_36_RA.fastq
mv data/split/GTCCGC_RA_GGGAGCTGAATGCAG.fastq data/renamed/OSKR_37_RA.fastq
mv data/split/GTCCGC_RA_GGTAGGATGATGCAG.fastq data/renamed/OSKR_38_RA.fastq
mv data/split/GTCCGC_RA_GGAATCCGTCTGCAG.fastq data/renamed/OSKR_39_RA.fastq
mv data/split/GTCCGC_RA_GGCACCTTACTGCAG.fastq data/renamed/OSKR_40_RA.fastq
mv data/split/GTCCGC_RA_GGGCCAAGACTGCAG.fastq data/renamed/OSKR_41_RA.fastq
mv data/split/ATGTCA_RA_GGACAAGCTATGCAG.fastq data/renamed/OSKR_42_RA.fastq
mv data/split/ATGTCA_RA_GGAACAACCATGCAG.fastq data/renamed/OSKR_43_RA.fastq
mv data/split/ATGTCA_RA_GGAGATCGCATGCAG.fastq data/renamed/OSKR_44_RA.fastq
mv data/split/ATGTCA_RA_GGCCGAAGTATGCAG.fastq data/renamed/MS_PC_01_RA.fastq
mv data/split/ATGTCA_RA_GGGATAGACATGCAG.fastq data/renamed/MS_PC_02_RA.fastq
mv data/split/ATGTCA_RA_GGTATCAGCATGCAG.fastq data/renamed/MS_PC_03_RA.fastq
mv data/split/ATGTCA_RA_GGAATGTTGCTGCAG.fastq data/renamed/MS_PC_04_RA.fastq
mv data/split/ATGTCA_RA_GGCCATCCTCTGCAG.fastq data/renamed/MS_PC_05_RA.fastq
mv data/split/ATGTCA_RA_GGAAACATCGTGCAG.fastq data/renamed/MS_PC_06_RA.fastq
mv data/split/ATGTCA_RA_GGAACCGAGATGCAG.fastq data/renamed/MS_PC_07_RA.fastq
mv data/split/ATGTCA_RA_GGAGCAGGAATGCAG.fastq data/renamed/MS_PC_08_RA.fastq
mv data/split/ATGTCA_RA_GGCCGTGAGATGCAG.fastq data/renamed/MS_PC_09_RA.fastq
mv data/split/ATGTCA_RA_GGGCCACATATGCAG.fastq data/renamed/MS_PC_10_RA.fastq
mv data/split/ATGTCA_RA_GGTCCGTCTATGCAG.fastq data/renamed/MS_PC_11_RA.fastq
mv data/split/ATGTCA_RA_GGACACTGACTGCAG.fastq data/renamed/MS_PC_12_RA.fastq
mv data/split/ATGTCA_RA_GGCCGACAACTGCAG.fastq data/renamed/MS_PC_13_RA.fastq
mv data/split/ATGTCA_RA_GGACATTGGCTGCAG.fastq data/renamed/MS_PC_14_RA.fastq
mv data/split/ATGTCA_RA_GGAACGCTTATGCAG.fastq data/renamed/MS_PC_15_RA.fastq
mv data/split/ATGTCA_RA_GGAGTCACTATGCAG.fastq data/renamed/MS_PC_16_RA.fastq
mv data/split/ATGTCA_RA_GGCCTCCTGATGCAG.fastq data/renamed/MS_PC_17_RA.fastq
mv data/split/ATGTCA_RA_GGGCGAGTAATGCAG.fastq data/renamed/MS_PC_18_RA.fastq
mv data/split/ATGTCA_RA_GGTCTTCACATGCAG.fastq data/renamed/MS_PC_19_RA.fastq
mv data/split/ATGTCA_RA_GGACAGATTCTGCAG.fastq data/renamed/MS_PC_20_RA.fastq
mv data/split/ATGTCA_RA_GGAGTCAAGCTGCAG.fastq data/renamed/MS_PC_21_RA.fastq
mv data/split/GTGAAA_RA_GGACAAGCTATGCAG.fastq data/renamed/KLS_2802-095_RA.fastq
mv data/split/GTGAAA_RA_GGAACAACCATGCAG.fastq data/renamed/KLS_2801-023_RA.fastq
mv data/split/GTGAAA_RA_GGAGATCGCATGCAG.fastq data/renamed/KLS_2802-097_RA.fastq
mv data/split/GTGAAA_RA_GGCCGAAGTATGCAG.fastq data/renamed/KLS_2804-002_RA.fastq
mv data/split/GTGAAA_RA_GGGATAGACATGCAG.fastq data/renamed/KLS_2804-004_RA.fastq
mv data/split/GTGAAA_RA_GGTATCAGCATGCAG.fastq data/renamed/KLS_2804-005_RA.fastq
mv data/split/GTGAAA_RA_GGAATGTTGCTGCAG.fastq data/renamed/KLS_2804-006_RA.fastq
mv data/split/GTGAAA_RA_GGCCATCCTCTGCAG.fastq data/renamed/KLS_2804-008_RA.fastq
mv data/split/GTGAAA_RA_GGAAACATCGTGCAG.fastq data/renamed/KLS_2804-011_RA.fastq
mv data/split/GTGAAA_RA_GGAACCGAGATGCAG.fastq data/renamed/KLS_2804-012_RA.fastq
mv data/split/GTGAAA_RA_GGAGCAGGAATGCAG.fastq data/renamed/KLS_2804-013_RA.fastq
mv data/split/GTGAAA_RA_GGCCGTGAGATGCAG.fastq data/renamed/KLS_2804-015_RA.fastq
mv data/split/GTGAAA_RA_GGGCCACATATGCAG.fastq data/renamed/KLS_2804-016_RA.fastq
mv data/split/GTGAAA_RA_GGTCCGTCTATGCAG.fastq data/renamed/KLS_2905-001_RA.fastq
mv data/split/GTGAAA_RA_GGACACTGACTGCAG.fastq data/renamed/KLS_2905-019_RA.fastq
mv data/split/GTGAAA_RA_GGCCGACAACTGCAG.fastq data/renamed/KLS_2905-023_RA.fastq
mv data/split/GTGAAA_RA_GGACATTGGCTGCAG.fastq data/renamed/KLS_2897-059_RA.fastq
mv data/split/GTGAAA_RA_GGAACGCTTATGCAG.fastq data/renamed/KLS_2897-060_RA.fastq
mv data/split/GTGAAA_RA_GGAGTCACTATGCAG.fastq data/renamed/KLS_3228-039_RA.fastq
mv data/split/GTGAAA_RA_GGCCTCCTGATGCAG.fastq data/renamed/KLS_3228-043_RA.fastq
mv data/split/GTGAAA_RA_GGGCGAGTAATGCAG.fastq data/renamed/KLS_3228-046_RA.fastq
mv data/split/GTGAAA_RA_GGTCTTCACATGCAG.fastq data/renamed/KLS_3228-047_RA.fastq
mv data/split/GTGAAA_RA_GGACAGATTCTGCAG.fastq data/renamed/KLS_3228-048_RA.fastq
mv data/split/GTGAAA_RA_GGAGTCAAGCTGCAG.fastq data/renamed/KLS_3228-049_RA.fastq
mv data/split/GTGAAA_RA_GGACCACTGTTGCAG.fastq data/renamed/KLS_3228-050_RA.fastq
mv data/split/GTGAAA_RA_GGAAGACGGATGCAG.fastq data/renamed/LRS_2728-012_RA.fastq
mv data/split/GTGAAA_RA_GGATCCTGTATGCAG.fastq data/renamed/LRS_2728-017_RA.fastq
mv data/split/GTGAAA_RA_GGCGAACTTATGCAG.fastq data/renamed/LRS_2728-020_RA.fastq
mv data/split/GTGAAA_RA_GGGCTAACGATGCAG.fastq data/renamed/LRS_2728-021_RA.fastq
mv data/split/GTGAAA_RA_GGTGAAGAGATGCAG.fastq data/renamed/LRS_2728-026_RA.fastq
mv data/split/GTGAAA_RA_GGAGATGTACTGCAG.fastq data/renamed/LRS_2728-029_RA.fastq
mv data/split/GTGAAA_RA_GGCCTCTATCTGCAG.fastq data/renamed/LRS_2728-033_RA.fastq
mv data/split/GTGAAA_RA_GGAACGTGATTGCAG.fastq data/renamed/LRS_2728-036_RA.fastq
mv data/split/GTGAAA_RA_GGAAGGTACATGCAG.fastq data/renamed/LRS_2728-040_RA.fastq
mv data/split/GTGAAA_RA_GGATTGAGGATGCAG.fastq data/renamed/LRS_2735-045_RA.fastq
mv data/split/GTGAAA_RA_GGCGACTGGATGCAG.fastq data/renamed/LRS_2735-076_RA.fastq
mv data/split/GTGAAA_RA_GGGCTCGGTATGCAG.fastq data/renamed/LRS_2735-077_RA.fastq
mv data/split/GTGAAA_RA_GGTGGAACAATGCAG.fastq data/renamed/LRS_2735-079_RA.fastq
mv data/split/GTGAAA_RA_GGAGCACCTCTGCAG.fastq data/renamed/LRS_2735-084_RA.fastq
mv data/split/GTGAAA_RA_GGCGACACACTGCAG.fastq data/renamed/LRS_2735-085_RA.fastq
mv data/split/GTGAAA_RA_GGCGCTGATCTGCAG.fastq data/renamed/LRS_2735-086_RA.fastq
mv data/split/GTGAAA_RA_GGACACAGAATGCAG.fastq data/renamed/LRS_2735-088_RA.fastq
mv data/split/GTGAAA_RA_GGCAACCACATGCAG.fastq data/renamed/LRS_2896-002_RA.fastq
mv data/split/GTGAAA_RA_GGCGCATACATGCAG.fastq data/renamed/LRS_2896-003_RA.fastq
mv data/split/GTGAAA_RA_GGGGAGAACATGCAG.fastq data/renamed/LRS_2896-004_RA.fastq
mv data/split/GTGAAA_RA_GGTGGCTTCATGCAG.fastq data/renamed/LRS_2896-006_RA.fastq
mv data/split/GTGAAA_RA_GGAGCCATGCTGCAG.fastq data/renamed/LRS_2896-007_RA.fastq
mv data/split/GTGAAA_RA_GGCGGATTGCTGCAG.fastq data/renamed/LRS_2896-008_RA.fastq
mv data/split/GTGAAA_RA_GGCAGATCTGTGCAG.fastq data/renamed/LRS_2896-010_RA.fastq
mv data/split/GTGAAA_RA_GGACAGCAGATGCAG.fastq data/renamed/LRS_2896-011_RA.fastq
mv data/split/GTGAAA_RA_GGCAAGACTATGCAG.fastq data/renamed/SNS_2894-072_RA.fastq
mv data/split/GTGAAA_RA_GGCTCAATGATGCAG.fastq data/renamed/SNS_2894-073_RA.fastq
mv data/split/GTGAAA_RA_GGGGTGCGAATGCAG.fastq data/renamed/SNS_2894-074_RA.fastq
mv data/split/GTGAAA_RA_GGTGGTGGTATGCAG.fastq data/renamed/SNS_2894-082_RA.fastq
mv data/split/GTGAAA_RA_GGAGGCTAACTGCAG.fastq data/renamed/SNS_2894-083_RA.fastq
mv data/split/GTGAAA_RA_GGCTAAGGTCTGCAG.fastq data/renamed/SNS_2894-084_RA.fastq
mv data/split/GTGAAA_RA_GGATGCCTAATGCAG.fastq data/renamed/SNS_2894-085_RA.fastq
mv data/split/GTGAAA_RA_GGACCTCCAATGCAG.fastq data/renamed/SNS_2894-086_RA.fastq
mv data/split/GTGAAA_RA_GGCAATGGAATGCAG.fastq data/renamed/SNS_2894-087_RA.fastq
mv data/split/GTGAAA_RA_GGCTGAGCCATGCAG.fastq data/renamed/SNS_2894-088_RA.fastq
mv data/split/GTGAAA_RA_GGGTACGCAATGCAG.fastq data/renamed/SNS_2894-089_RA.fastq
mv data/split/GTGAAA_RA_GGTTCACGCATGCAG.fastq data/renamed/SNS_2894-090_RA.fastq
mv data/split/GTGAAA_RA_GGATAGCGACTGCAG.fastq data/renamed/SNS_2894-091_RA.fastq
mv data/split/GTGAAA_RA_GGGAACAGGCTGCAG.fastq data/renamed/SNS_2894-092_RA.fastq
mv data/split/GTGAAA_RA_GGAACGAACGTGCAG.fastq data/renamed/SNS_2894-093_RA.fastq
mv data/split/GTGAAA_RA_GGACGCTCGATGCAG.fastq data/renamed/SNS_2894-094_RA.fastq
mv data/split/GTGAAA_RA_GGCACTTCGATGCAG.fastq data/renamed/SNS_2894-095_RA.fastq
mv data/split/GTGAAA_RA_GGCTGGCATATGCAG.fastq data/renamed/SNS_2894-096_RA.fastq
mv data/split/GTGAAA_RA_GGGTCGTAGATGCAG.fastq data/renamed/SNS_2898-077_RA.fastq
mv data/split/GTGAAA_RA_GGACACGAGATGCAG.fastq data/renamed/SNS_2898-084_RA.fastq
mv data/split/GTGAAA_RA_GGACGACAAGTGCAG.fastq data/renamed/SNS_2949_043_RA.fastq
mv data/split/GTGAAA_RA_GGGACAGTGCTGCAG.fastq data/renamed/SNS_2801-015_RA.fastq
mv data/split/GTGAAA_RA_GGAGTACAAGTGCAG.fastq data/renamed/SNS_2801-017_RA.fastq
mv data/split/GTGAAA_RA_GGACGTATCATGCAG.fastq data/renamed/SNS_2801-018_RA.fastq
mv data/split/GTGAAA_RA_GGCAGCGTTATGCAG.fastq data/renamed/SNS_2801-025_RA.fastq
mv data/split/GTGAAA_RA_GGGAATCTGATGCAG.fastq data/renamed/KSS_3734-001_RA.fastq
mv data/split/GTGAAA_RA_GGGTCTGTCATGCAG.fastq data/renamed/KSS_3734-002_RA.fastq
mv data/split/GTGAAA_RA_GGAAGAGATCTGCAG.fastq data/renamed/KSS_3734-003_RA.fastq
mv data/split/GTGAAA_RA_GGATTGGCTCTGCAG.fastq data/renamed/KSS_3734-004_RA.fastq
mv data/split/GTGAAA_RA_GGGAGTTAGCTGCAG.fastq data/renamed/KSS_3734-005_RA.fastq
mv data/split/GTGAAA_RA_GGCATCAAGTTGCAG.fastq data/renamed/KSS_3734-006_RA.fastq
mv data/split/GTGAAA_RA_GGACTATGCATGCAG.fastq data/renamed/KSS_3734-007_RA.fastq
mv data/split/GTGAAA_RA_GGCATACCAATGCAG.fastq data/renamed/KSS_3734-008_RA.fastq
mv data/split/GTGAAA_RA_GGGACTAGTATGCAG.fastq data/renamed/KSS_3734-009_RA.fastq
mv data/split/GTGAAA_RA_GGGTGTTCTATGCAG.fastq data/renamed/KSS_3734-010_RA.fastq
mv data/split/GTGAAA_RA_GGAAGGACACTGCAG.fastq data/renamed/KSS_3734-011_RA.fastq
mv data/split/GTGAAA_RA_GGCAAGGAGCTGCAG.fastq data/renamed/KSS_3734-012_RA.fastq
mv data/split/GTGAAA_RA_GGGATGAATCTGCAG.fastq data/renamed/KSS_3734-013_RA.fastq
mv data/split/GTGAAA_RA_GGAGTGGTCATGCAG.fastq data/renamed/KSS_3734-013_RA.fastq
mv data/split/GTGAAA_RA_GGAGAGTCAATGCAG.fastq data/renamed/KSS_3734-014_RA.fastq
mv data/split/GTGAAA_RA_GGCCAGTTCATGCAG.fastq data/renamed/KSS_3734-015_RA.fastq
mv data/split/GTGAAA_RA_GGGAGCTGAATGCAG.fastq data/renamed/KSS_3734-016_RA.fastq
mv data/split/AGTCAA_RB_GGACAAGCTATGCAG.fastq data/renamed/WS_DC01_RB.fastq
mv data/split/AGTCAA_RB_GGAACAACCATGCAG.fastq data/renamed/WS_DC02_RB.fastq
mv data/split/AGTCAA_RB_GGAGATCGCATGCAG.fastq data/renamed/WS_DC03_RB.fastq
mv data/split/AGTCAA_RB_GGCCGAAGTATGCAG.fastq data/renamed/WS_DC04_RB.fastq
mv data/split/AGTCAA_RB_GGGATAGACATGCAG.fastq data/renamed/WS_DC05_RB.fastq
mv data/split/AGTCAA_RB_GGTATCAGCATGCAG.fastq data/renamed/WS_DC06_RB.fastq
mv data/split/AGTCAA_RB_GGAATGTTGCTGCAG.fastq data/renamed/WS_DC07_RB.fastq
mv data/split/AGTCAA_RB_GGCCATCCTCTGCAG.fastq data/renamed/WS_DC08_RB.fastq
mv data/split/AGTCAA_RB_GGAAACATCGTGCAG.fastq data/renamed/WS_DC09_RB.fastq
mv data/split/AGTCAA_RB_GGAACCGAGATGCAG.fastq data/renamed/WS_DC10_RB.fastq
mv data/split/AGTCAA_RB_GGAGCAGGAATGCAG.fastq data/renamed/WS_DC11_RB.fastq
mv data/split/AGTCAA_RB_GGCCGTGAGATGCAG.fastq data/renamed/WS_DC12_RB.fastq
mv data/split/AGTCAA_RB_GGGCCACATATGCAG.fastq data/renamed/WS_DC13_RB.fastq
mv data/split/AGTCAA_RB_GGTCCGTCTATGCAG.fastq data/renamed/WS_DC14_RB.fastq
mv data/split/AGTCAA_RB_GGACACTGACTGCAG.fastq data/renamed/WS_DC15_RB.fastq
mv data/split/AGTCAA_RB_GGCCGACAACTGCAG.fastq data/renamed/WS_TMC01_RB.fastq
mv data/split/AGTCAA_RB_GGACATTGGCTGCAG.fastq data/renamed/WS_TMC02_RB.fastq
mv data/split/AGTCAA_RB_GGAACGCTTATGCAG.fastq data/renamed/WS_TMC03_RB.fastq
mv data/split/AGTCAA_RB_GGAGTCACTATGCAG.fastq data/renamed/WS_TMC04_RB.fastq
mv data/split/AGTCAA_RB_GGCCTCCTGATGCAG.fastq data/renamed/WS_TMC05_RB.fastq
mv data/split/AGTCAA_RB_GGGCGAGTAATGCAG.fastq data/renamed/WS_TMC06_RB.fastq
mv data/split/AGTCAA_RB_GGTCTTCACATGCAG.fastq data/renamed/WS_TMC07_RB.fastq
mv data/split/AGTCAA_RB_GGACAGATTCTGCAG.fastq data/renamed/WS_TMC08_RB.fastq
mv data/split/AGTCAA_RB_GGAGTCAAGCTGCAG.fastq data/renamed/WS_TMC09_RB.fastq
mv data/split/AGTCAA_RB_GGACCACTGTTGCAG.fastq data/renamed/WS_TMC10_RB.fastq
mv data/split/AGTCAA_RB_GGAAGACGGATGCAG.fastq data/renamed/WS_TMC11_RB.fastq
mv data/split/AGTCAA_RB_GGATCCTGTATGCAG.fastq data/renamed/WS_TMC12_RB.fastq
mv data/split/AGTCAA_RB_GGCGAACTTATGCAG.fastq data/renamed/WS_TMC13_RB.fastq
mv data/split/AGTCAA_RB_GGGCTAACGATGCAG.fastq data/renamed/WS_TMC14_RB.fastq
mv data/split/AGTCAA_RB_GGTGAAGAGATGCAG.fastq data/renamed/WS_HC1_RB.fastq
mv data/split/AGTCAA_RB_GGAGATGTACTGCAG.fastq data/renamed/WS_TMC15_RB.fastq
mv data/split/AGTCAA_RB_GGCCTCTATCTGCAG.fastq data/renamed/WS_HC2_RB.fastq
mv data/split/AGTCAA_RB_GGAACGTGATTGCAG.fastq data/renamed/WS_HC3_RB.fastq
mv data/split/AGTCAA_RB_GGAAGGTACATGCAG.fastq data/renamed/WS_HC4_RB.fastq
mv data/split/AGTCAA_RB_GGATTGAGGATGCAG.fastq data/renamed/WS_HC5_RB.fastq
mv data/split/AGTCAA_RB_GGCGACTGGATGCAG.fastq data/renamed/WS_HC6_RB.fastq
mv data/split/AGTCAA_RB_GGGCTCGGTATGCAG.fastq data/renamed/WS_HC7_RB.fastq
mv data/split/AGTCAA_RB_GGTGGAACAATGCAG.fastq data/renamed/WS_HC8_RB.fastq
mv data/split/AGTCAA_RB_GGAGCACCTCTGCAG.fastq data/renamed/WCS_01_RB.fastq
mv data/split/AGTCAA_RB_GGCGACACACTGCAG.fastq data/renamed/WCS_02_RB.fastq
mv data/split/AGTCAA_RB_GGCGCTGATCTGCAG.fastq data/renamed/WCS_03_RB.fastq
mv data/split/AGTCAA_RB_GGACACAGAATGCAG.fastq data/renamed/WCS_04_RB.fastq
mv data/split/AGTCAA_RB_GGCAACCACATGCAG.fastq data/renamed/WCS_05_RB.fastq
mv data/split/AGTCAA_RB_GGCGCATACATGCAG.fastq data/renamed/WCS_06_RB.fastq
mv data/split/AGTCAA_RB_GGGGAGAACATGCAG.fastq data/renamed/WCS_07_RB.fastq
mv data/split/AGTCAA_RB_GGTGGCTTCATGCAG.fastq data/renamed/WCS_08_RB.fastq
mv data/split/AGTCAA_RB_GGAGCCATGCTGCAG.fastq data/renamed/WCS_09_RB.fastq
mv data/split/AGTCAA_RB_GGCGGATTGCTGCAG.fastq data/renamed/WCS_10_RB.fastq
mv data/split/AGTCAA_RB_GGCAGATCTGTGCAG.fastq data/renamed/WCS_11_RB.fastq
mv data/split/AGTCAA_RB_GGACAGCAGATGCAG.fastq data/renamed/WCS_12_RB.fastq
mv data/split/AGTCAA_RB_GGCAAGACTATGCAG.fastq data/renamed/WCS_13_RB.fastq
mv data/split/AGTCAA_RB_GGCTCAATGATGCAG.fastq data/renamed/WCS_14_RB.fastq
mv data/split/AGTCAA_RB_GGGGTGCGAATGCAG.fastq data/renamed/WCS_15_RB.fastq
mv data/split/AGTCAA_RB_GGTGGTGGTATGCAG.fastq data/renamed/WCS_16_RB.fastq
mv data/split/AGTCAA_RB_GGAGGCTAACTGCAG.fastq data/renamed/WCS_17_RB.fastq
mv data/split/AGTCAA_RB_GGCTAAGGTCTGCAG.fastq data/renamed/WCS_18_RB.fastq
mv data/split/AGTCAA_RB_GGATGCCTAATGCAG.fastq data/renamed/WCS_19_RB.fastq
mv data/split/AGTCAA_RB_GGACCTCCAATGCAG.fastq data/renamed/WCS_20_RB.fastq
mv data/split/AGTCAA_RB_GGCAATGGAATGCAG.fastq data/renamed/WCS_21_RB.fastq
mv data/split/AGTCAA_RB_GGCTGAGCCATGCAG.fastq data/renamed/WCS_22_RB.fastq
mv data/split/AGTCAA_RB_GGGTACGCAATGCAG.fastq data/renamed/WCS_23_RB.fastq
mv data/split/AGTCAA_RB_GGTTCACGCATGCAG.fastq data/renamed/WCS_24_RB.fastq
mv data/split/AGTCAA_RB_GGATAGCGACTGCAG.fastq data/renamed/WCS_25_RB.fastq
mv data/split/AGTCAA_RB_GGGAACAGGCTGCAG.fastq data/renamed/WCS_26_RB.fastq
mv data/split/AGTCAA_RB_GGAACGAACGTGCAG.fastq data/renamed/WCS_27_RB.fastq
mv data/split/AGTCAA_RB_GGACGCTCGATGCAG.fastq data/renamed/S_TR_01_RB.fastq
mv data/split/AGTCAA_RB_GGCACTTCGATGCAG.fastq data/renamed/S_TR_02_RB.fastq
mv data/split/AGTCAA_RB_GGCTGGCATATGCAG.fastq data/renamed/S_TR_03_RB.fastq
mv data/split/AGTCAA_RB_GGGTCGTAGATGCAG.fastq data/renamed/S_TR_04_RB.fastq
mv data/split/AGTCAA_RB_GGACACGAGATGCAG.fastq data/renamed/S_TR_05_RB.fastq
mv data/split/AGTCAA_RB_GGACGACAAGTGCAG.fastq data/renamed/S_TR_06_RB.fastq
mv data/split/AGTCAA_RB_GGGACAGTGCTGCAG.fastq data/renamed/S_TR_07_RB.fastq
mv data/split/AGTCAA_RB_GGAGTACAAGTGCAG.fastq data/renamed/S_TR_08_RB.fastq
mv data/split/AGTCAA_RB_GGACGTATCATGCAG.fastq data/renamed/S_TR_09_RB.fastq
mv data/split/AGTCAA_RB_GGCAGCGTTATGCAG.fastq data/renamed/S_TR_10_RB.fastq
mv data/split/AGTCAA_RB_GGGAATCTGATGCAG.fastq data/renamed/S_TR_11_RB.fastq
mv data/split/AGTCAA_RB_GGGTCTGTCATGCAG.fastq data/renamed/S_TR_12_RB.fastq
mv data/split/AGTCAA_RB_GGAAGAGATCTGCAG.fastq data/renamed/S_TR_13_RB.fastq
mv data/split/AGTCAA_RB_GGATTGGCTCTGCAG.fastq data/renamed/S_TR_14_RB.fastq
mv data/split/AGTCAA_RB_GGGAGTTAGCTGCAG.fastq data/renamed/S_TR_15_RB.fastq
mv data/split/AGTCAA_RB_GGCATCAAGTTGCAG.fastq data/renamed/S_TR_16_RB.fastq
mv data/split/AGTCAA_RB_GGACTATGCATGCAG.fastq data/renamed/S_TR_17_RB.fastq
mv data/split/AGTCAA_RB_GGCATACCAATGCAG.fastq data/renamed/S_TR_18_RB.fastq
mv data/split/AGTCAA_RB_GGGACTAGTATGCAG.fastq data/renamed/S_TR_19_RB.fastq
mv data/split/AGTCAA_RB_GGGTGTTCTATGCAG.fastq data/renamed/S_TR_20_RB.fastq
mv data/split/AGTCAA_RB_GGAAGGACACTGCAG.fastq data/renamed/TS_EFCR_01_RB.fastq
mv data/split/AGTCAA_RB_GGCAAGGAGCTGCAG.fastq data/renamed/TS_EFCR_02_RB.fastq
mv data/split/AGTCAA_RB_GGGATGAATCTGCAG.fastq data/renamed/TS_EFCR_03_RB.fastq
mv data/split/AGTCAA_RB_GGAGTGGTCATGCAG.fastq data/renamed/TS_EFCR_04_RB.fastq
mv data/split/AGTCAA_RB_GGAGAGTCAATGCAG.fastq data/renamed/TS_EFCR_05_RB.fastq
mv data/split/AGTCAA_RB_GGCCAGTTCATGCAG.fastq data/renamed/TS_EFCR_06_RB.fastq
mv data/split/AGTCAA_RB_GGGAGCTGAATGCAG.fastq data/renamed/TS_EFCR_07_RB.fastq
mv data/split/AGTCAA_RB_GGTAGGATGATGCAG.fastq data/renamed/TS_EFCR_08_RB.fastq
mv data/split/AGTCAA_RB_GGAATCCGTCTGCAG.fastq data/renamed/TS_EFCR_09_RB.fastq
mv data/split/AGTCAA_RB_GGCACCTTACTGCAG.fastq data/renamed/TS_EFCR_10_RB.fastq
mv data/split/AGTCAA_RB_GGGCCAAGACTGCAG.fastq data/renamed/TS_EFCR_11_RB.fastq
mv data/split/GTCCGC_RB_GGACAAGCTATGCAG.fastq data/renamed/TS_EFCR_12_RB.fastq
mv data/split/GTCCGC_RB_GGAACAACCATGCAG.fastq data/renamed/TS_EFCR_13_RB.fastq
mv data/split/GTCCGC_RB_GGAGATCGCATGCAG.fastq data/renamed/TS_EFCR_14_RB.fastq
mv data/split/GTCCGC_RB_GGCCGAAGTATGCAG.fastq data/renamed/TS_EFCR_15_RB.fastq
mv data/split/GTCCGC_RB_GGGATAGACATGCAG.fastq data/renamed/TS_EFCR_16_RB.fastq
mv data/split/GTCCGC_RB_GGTATCAGCATGCAG.fastq data/renamed/TS_EFCR_17_RB.fastq
mv data/split/GTCCGC_RB_GGAATGTTGCTGCAG.fastq data/renamed/TS_EFCR_18_RB.fastq
mv data/split/GTCCGC_RB_GGCCATCCTCTGCAG.fastq data/renamed/TS_EFCR_19_RB.fastq
mv data/split/GTCCGC_RB_GGAAACATCGTGCAG.fastq data/renamed/934-002_RB.fastq
mv data/split/GTCCGC_RB_GGAACCGAGATGCAG.fastq data/renamed/934-003_RB.fastq
mv data/split/GTCCGC_RB_GGAGCAGGAATGCAG.fastq data/renamed/934-004_RB.fastq
mv data/split/GTCCGC_RB_GGCCGTGAGATGCAG.fastq data/renamed/934-005_RB.fastq
mv data/split/GTCCGC_RB_GGGCCACATATGCAG.fastq data/renamed/934-006_RB.fastq
mv data/split/GTCCGC_RB_GGTCCGTCTATGCAG.fastq data/renamed/934-007_RB.fastq
mv data/split/GTCCGC_RB_GGACACTGACTGCAG.fastq data/renamed/934-008_RB.fastq
mv data/split/GTCCGC_RB_GGCCGACAACTGCAG.fastq data/renamed/934-009_RB.fastq
mv data/split/GTCCGC_RB_GGACATTGGCTGCAG.fastq data/renamed/934-010_RB.fastq
mv data/split/GTCCGC_RB_GGAACGCTTATGCAG.fastq data/renamed/934-011_RB.fastq
mv data/split/GTCCGC_RB_GGAGTCACTATGCAG.fastq data/renamed/934-012_RB.fastq
mv data/split/GTCCGC_RB_GGCCTCCTGATGCAG.fastq data/renamed/934-013_RB.fastq
mv data/split/GTCCGC_RB_GGGCGAGTAATGCAG.fastq data/renamed/945-006_RB.fastq
mv data/split/GTCCGC_RB_GGTCTTCACATGCAG.fastq data/renamed/945-007_RB.fastq
mv data/split/GTCCGC_RB_GGACAGATTCTGCAG.fastq data/renamed/945-008_RB.fastq
mv data/split/GTCCGC_RB_GGAGTCAAGCTGCAG.fastq data/renamed/945-009_RB.fastq
mv data/split/GTCCGC_RB_GGACCACTGTTGCAG.fastq data/renamed/945-010_RB.fastq
mv data/split/GTCCGC_RB_GGAAGACGGATGCAG.fastq data/renamed/1208-008_RB.fastq
mv data/split/GTCCGC_RB_GGATCCTGTATGCAG.fastq data/renamed/1208-009_RB.fastq
mv data/split/GTCCGC_RB_GGCGAACTTATGCAG.fastq data/renamed/1208-010_RB.fastq
mv data/split/GTCCGC_RB_GGGCTAACGATGCAG.fastq data/renamed/1208-011_RB.fastq
mv data/split/GTCCGC_RB_GGTGAAGAGATGCAG.fastq data/renamed/1208-012_RB.fastq
mv data/split/GTCCGC_RB_GGAGATGTACTGCAG.fastq data/renamed/1208-013_RB.fastq
mv data/split/GTCCGC_RB_GGCCTCTATCTGCAG.fastq data/renamed/1208-014_RB.fastq
mv data/split/GTCCGC_RB_GGAACGTGATTGCAG.fastq data/renamed/1208-015_RB.fastq
mv data/split/GTCCGC_RB_GGAAGGTACATGCAG.fastq data/renamed/1208-016_RB.fastq
mv data/split/GTCCGC_RB_GGATTGAGGATGCAG.fastq data/renamed/1208-017_RB.fastq
mv data/split/GTCCGC_RB_GGCGACTGGATGCAG.fastq data/renamed/1208-058_RB.fastq
mv data/split/GTCCGC_RB_GGGCTCGGTATGCAG.fastq data/renamed/1208-059_RB.fastq
mv data/split/GTCCGC_RB_GGTGGAACAATGCAG.fastq data/renamed/1208-060_RB.fastq
mv data/split/GTCCGC_RB_GGAGCACCTCTGCAG.fastq data/renamed/1208-061_RB.fastq
mv data/split/GTCCGC_RB_GGCGACACACTGCAG.fastq data/renamed/1208-062_RB.fastq
mv data/split/GTCCGC_RB_GGCGCTGATCTGCAG.fastq data/renamed/1208-063_RB.fastq
mv data/split/GTCCGC_RB_GGACACAGAATGCAG.fastq data/renamed/1208-064_RB.fastq
mv data/split/GTCCGC_RB_GGCAACCACATGCAG.fastq data/renamed/1208-065_RB.fastq
mv data/split/GTCCGC_RB_GGCGCATACATGCAG.fastq data/renamed/1208-066_RB.fastq
mv data/split/GTCCGC_RB_GGGGAGAACATGCAG.fastq data/renamed/1208-067_RB.fastq
mv data/split/GTCCGC_RB_GGTGGCTTCATGCAG.fastq data/renamed/1272-011_RB.fastq
mv data/split/GTCCGC_RB_GGAGCCATGCTGCAG.fastq data/renamed/1272-012_RB.fastq
mv data/split/GTCCGC_RB_GGCGGATTGCTGCAG.fastq data/renamed/1272-013_RB.fastq
mv data/split/GTCCGC_RB_GGCAGATCTGTGCAG.fastq data/renamed/1272-014_RB.fastq
mv data/split/GTCCGC_RB_GGACAGCAGATGCAG.fastq data/renamed/1272-015_RB.fastq
mv data/split/GTCCGC_RB_GGCAAGACTATGCAG.fastq data/renamed/1272-016_RB.fastq
mv data/split/GTCCGC_RB_GGCTCAATGATGCAG.fastq data/renamed/1272-017_RB.fastq
mv data/split/GTCCGC_RB_GGGGTGCGAATGCAG.fastq data/renamed/1272-018_RB.fastq
mv data/split/GTCCGC_RB_GGTGGTGGTATGCAG.fastq data/renamed/1272-019_RB.fastq
mv data/split/GTCCGC_RB_GGAGGCTAACTGCAG.fastq data/renamed/1272-020_RB.fastq
mv data/split/GTCCGC_RB_GGCTAAGGTCTGCAG.fastq data/renamed/OSKR_1_RB.fastq
mv data/split/GTCCGC_RB_GGATGCCTAATGCAG.fastq data/renamed/OSKR_2_RB.fastq
mv data/split/GTCCGC_RB_GGACCTCCAATGCAG.fastq data/renamed/OSKR_3_RB.fastq
mv data/split/GTCCGC_RB_GGCAATGGAATGCAG.fastq data/renamed/OSKR_4_RB.fastq
mv data/split/GTCCGC_RB_GGCTGAGCCATGCAG.fastq data/renamed/OSKR_5_RB.fastq
mv data/split/GTCCGC_RB_GGGTACGCAATGCAG.fastq data/renamed/OSKR_6_RB.fastq
mv data/split/GTCCGC_RB_GGTTCACGCATGCAG.fastq data/renamed/OSKR_7_RB.fastq
mv data/split/GTCCGC_RB_GGATAGCGACTGCAG.fastq data/renamed/OSKR_8_RB.fastq
mv data/split/GTCCGC_RB_GGGAACAGGCTGCAG.fastq data/renamed/OSKR_9_RB.fastq
mv data/split/GTCCGC_RB_GGAACGAACGTGCAG.fastq data/renamed/OSKR_10_RB.fastq
mv data/split/GTCCGC_RB_GGACGCTCGATGCAG.fastq data/renamed/OSKR_11_RB.fastq
mv data/split/GTCCGC_RB_GGCACTTCGATGCAG.fastq data/renamed/OSKR_12_RB.fastq
mv data/split/GTCCGC_RB_GGCTGGCATATGCAG.fastq data/renamed/OSKR_13_RB.fastq
mv data/split/GTCCGC_RB_GGGTCGTAGATGCAG.fastq data/renamed/OSKR_14_RB.fastq
mv data/split/GTCCGC_RB_GGACACGAGATGCAG.fastq data/renamed/OSKR_15_RB.fastq
mv data/split/GTCCGC_RB_GGACGACAAGTGCAG.fastq data/renamed/OSKR_16_RB.fastq
mv data/split/GTCCGC_RB_GGGACAGTGCTGCAG.fastq data/renamed/OSKR_17_RB.fastq
mv data/split/GTCCGC_RB_GGAGTACAAGTGCAG.fastq data/renamed/OSKR_18_RB.fastq
mv data/split/GTCCGC_RB_GGACGTATCATGCAG.fastq data/renamed/OSKR_19_RB.fastq
mv data/split/GTCCGC_RB_GGCAGCGTTATGCAG.fastq data/renamed/OSKR_20_RB.fastq
mv data/split/GTCCGC_RB_GGGAATCTGATGCAG.fastq data/renamed/OSKR_21_RB.fastq
mv data/split/GTCCGC_RB_GGGTCTGTCATGCAG.fastq data/renamed/OSKR_22_RB.fastq
mv data/split/GTCCGC_RB_GGAAGAGATCTGCAG.fastq data/renamed/OSKR_23_RB.fastq
mv data/split/GTCCGC_RB_GGATTGGCTCTGCAG.fastq data/renamed/OSKR_24_RB.fastq
mv data/split/GTCCGC_RB_GGGAGTTAGCTGCAG.fastq data/renamed/OSKR_25_RB.fastq
mv data/split/GTCCGC_RB_GGCATCAAGTTGCAG.fastq data/renamed/OSKR_26_RB.fastq
mv data/split/GTCCGC_RB_GGACTATGCATGCAG.fastq data/renamed/OSKR_27_RB.fastq
mv data/split/GTCCGC_RB_GGCATACCAATGCAG.fastq data/renamed/OSKR_28_RB.fastq
mv data/split/GTCCGC_RB_GGGACTAGTATGCAG.fastq data/renamed/OSKR_29_RB.fastq
mv data/split/GTCCGC_RB_GGGTGTTCTATGCAG.fastq data/renamed/OSKR_30_RB.fastq
mv data/split/GTCCGC_RB_GGAAGGACACTGCAG.fastq data/renamed/OSKR_31_RB.fastq
mv data/split/GTCCGC_RB_GGCAAGGAGCTGCAG.fastq data/renamed/OSKR_32_RB.fastq
mv data/split/GTCCGC_RB_GGGATGAATCTGCAG.fastq data/renamed/OSKR_33_RB.fastq
mv data/split/GTCCGC_RB_GGAGTGGTCATGCAG.fastq data/renamed/OSKR_34_RB.fastq
mv data/split/GTCCGC_RB_GGAGAGTCAATGCAG.fastq data/renamed/OSKR_35_RB.fastq
mv data/split/GTCCGC_RB_GGCCAGTTCATGCAG.fastq data/renamed/OSKR_36_RB.fastq
mv data/split/GTCCGC_RB_GGGAGCTGAATGCAG.fastq data/renamed/OSKR_37_RB.fastq
mv data/split/GTCCGC_RB_GGTAGGATGATGCAG.fastq data/renamed/OSKR_38_RB.fastq
mv data/split/GTCCGC_RB_GGAATCCGTCTGCAG.fastq data/renamed/OSKR_39_RB.fastq
mv data/split/GTCCGC_RB_GGCACCTTACTGCAG.fastq data/renamed/OSKR_40_RB.fastq
mv data/split/GTCCGC_RB_GGGCCAAGACTGCAG.fastq data/renamed/OSKR_41_RB.fastq
mv data/split/ATGTCA_RB_GGACAAGCTATGCAG.fastq data/renamed/OSKR_42_RB.fastq
mv data/split/ATGTCA_RB_GGAACAACCATGCAG.fastq data/renamed/OSKR_43_RB.fastq
mv data/split/ATGTCA_RB_GGAGATCGCATGCAG.fastq data/renamed/OSKR_44_RB.fastq
mv data/split/ATGTCA_RB_GGCCGAAGTATGCAG.fastq data/renamed/MS_PC_01_RB.fastq
mv data/split/ATGTCA_RB_GGGATAGACATGCAG.fastq data/renamed/MS_PC_02_RB.fastq
mv data/split/ATGTCA_RB_GGTATCAGCATGCAG.fastq data/renamed/MS_PC_03_RB.fastq
mv data/split/ATGTCA_RB_GGAATGTTGCTGCAG.fastq data/renamed/MS_PC_04_RB.fastq
mv data/split/ATGTCA_RB_GGCCATCCTCTGCAG.fastq data/renamed/MS_PC_05_RB.fastq
mv data/split/ATGTCA_RB_GGAAACATCGTGCAG.fastq data/renamed/MS_PC_06_RB.fastq
mv data/split/ATGTCA_RB_GGAACCGAGATGCAG.fastq data/renamed/MS_PC_07_RB.fastq
mv data/split/ATGTCA_RB_GGAGCAGGAATGCAG.fastq data/renamed/MS_PC_08_RB.fastq
mv data/split/ATGTCA_RB_GGCCGTGAGATGCAG.fastq data/renamed/MS_PC_09_RB.fastq
mv data/split/ATGTCA_RB_GGGCCACATATGCAG.fastq data/renamed/MS_PC_10_RB.fastq
mv data/split/ATGTCA_RB_GGTCCGTCTATGCAG.fastq data/renamed/MS_PC_11_RB.fastq
mv data/split/ATGTCA_RB_GGACACTGACTGCAG.fastq data/renamed/MS_PC_12_RB.fastq
mv data/split/ATGTCA_RB_GGCCGACAACTGCAG.fastq data/renamed/MS_PC_13_RB.fastq
mv data/split/ATGTCA_RB_GGACATTGGCTGCAG.fastq data/renamed/MS_PC_14_RB.fastq
mv data/split/ATGTCA_RB_GGAACGCTTATGCAG.fastq data/renamed/MS_PC_15_RB.fastq
mv data/split/ATGTCA_RB_GGAGTCACTATGCAG.fastq data/renamed/MS_PC_16_RB.fastq
mv data/split/ATGTCA_RB_GGCCTCCTGATGCAG.fastq data/renamed/MS_PC_17_RB.fastq
mv data/split/ATGTCA_RB_GGGCGAGTAATGCAG.fastq data/renamed/MS_PC_18_RB.fastq
mv data/split/ATGTCA_RB_GGTCTTCACATGCAG.fastq data/renamed/MS_PC_19_RB.fastq
mv data/split/ATGTCA_RB_GGACAGATTCTGCAG.fastq data/renamed/MS_PC_20_RB.fastq
mv data/split/ATGTCA_RB_GGAGTCAAGCTGCAG.fastq data/renamed/MS_PC_21_RB.fastq
mv data/split/GTGAAA_RB_GGACAAGCTATGCAG.fastq data/renamed/KLS_2802-095_RB.fastq
mv data/split/GTGAAA_RB_GGAACAACCATGCAG.fastq data/renamed/KLS_2801-023_RB.fastq
mv data/split/GTGAAA_RB_GGAGATCGCATGCAG.fastq data/renamed/KLS_2802-097_RB.fastq
mv data/split/GTGAAA_RB_GGCCGAAGTATGCAG.fastq data/renamed/KLS_2804-002_RB.fastq
mv data/split/GTGAAA_RB_GGGATAGACATGCAG.fastq data/renamed/KLS_2804-004_RB.fastq
mv data/split/GTGAAA_RB_GGTATCAGCATGCAG.fastq data/renamed/KLS_2804-005_RB.fastq
mv data/split/GTGAAA_RB_GGAATGTTGCTGCAG.fastq data/renamed/KLS_2804-006_RB.fastq
mv data/split/GTGAAA_RB_GGCCATCCTCTGCAG.fastq data/renamed/KLS_2804-008_RB.fastq
mv data/split/GTGAAA_RB_GGAAACATCGTGCAG.fastq data/renamed/KLS_2804-011_RB.fastq
mv data/split/GTGAAA_RB_GGAACCGAGATGCAG.fastq data/renamed/KLS_2804-012_RB.fastq
mv data/split/GTGAAA_RB_GGAGCAGGAATGCAG.fastq data/renamed/KLS_2804-013_RB.fastq
mv data/split/GTGAAA_RB_GGCCGTGAGATGCAG.fastq data/renamed/KLS_2804-015_RB.fastq
mv data/split/GTGAAA_RB_GGGCCACATATGCAG.fastq data/renamed/KLS_2804-016_RB.fastq
mv data/split/GTGAAA_RB_GGTCCGTCTATGCAG.fastq data/renamed/KLS_2905-001_RB.fastq
mv data/split/GTGAAA_RB_GGACACTGACTGCAG.fastq data/renamed/KLS_2905-019_RB.fastq
mv data/split/GTGAAA_RB_GGCCGACAACTGCAG.fastq data/renamed/KLS_2905-023_RB.fastq
mv data/split/GTGAAA_RB_GGACATTGGCTGCAG.fastq data/renamed/KLS_2897-059_RB.fastq
mv data/split/GTGAAA_RB_GGAACGCTTATGCAG.fastq data/renamed/KLS_2897-060_RB.fastq
mv data/split/GTGAAA_RB_GGAGTCACTATGCAG.fastq data/renamed/KLS_3228-039_RB.fastq
mv data/split/GTGAAA_RB_GGCCTCCTGATGCAG.fastq data/renamed/KLS_3228-043_RB.fastq
mv data/split/GTGAAA_RB_GGGCGAGTAATGCAG.fastq data/renamed/KLS_3228-046_RB.fastq
mv data/split/GTGAAA_RB_GGTCTTCACATGCAG.fastq data/renamed/KLS_3228-047_RB.fastq
mv data/split/GTGAAA_RB_GGACAGATTCTGCAG.fastq data/renamed/KLS_3228-048_RB.fastq
mv data/split/GTGAAA_RB_GGAGTCAAGCTGCAG.fastq data/renamed/KLS_3228-049_RB.fastq
mv data/split/GTGAAA_RB_GGACCACTGTTGCAG.fastq data/renamed/KLS_3228-050_RB.fastq
mv data/split/GTGAAA_RB_GGAAGACGGATGCAG.fastq data/renamed/LRS_2728-012_RB.fastq
mv data/split/GTGAAA_RB_GGATCCTGTATGCAG.fastq data/renamed/LRS_2728-017_RB.fastq
mv data/split/GTGAAA_RB_GGCGAACTTATGCAG.fastq data/renamed/LRS_2728-020_RB.fastq
mv data/split/GTGAAA_RB_GGGCTAACGATGCAG.fastq data/renamed/LRS_2728-021_RB.fastq
mv data/split/GTGAAA_RB_GGTGAAGAGATGCAG.fastq data/renamed/LRS_2728-026_RB.fastq
mv data/split/GTGAAA_RB_GGAGATGTACTGCAG.fastq data/renamed/LRS_2728-029_RB.fastq
mv data/split/GTGAAA_RB_GGCCTCTATCTGCAG.fastq data/renamed/LRS_2728-033_RB.fastq
mv data/split/GTGAAA_RB_GGAACGTGATTGCAG.fastq data/renamed/LRS_2728-036_RB.fastq
mv data/split/GTGAAA_RB_GGAAGGTACATGCAG.fastq data/renamed/LRS_2728-040_RB.fastq
mv data/split/GTGAAA_RB_GGATTGAGGATGCAG.fastq data/renamed/LRS_2735-045_RB.fastq
mv data/split/GTGAAA_RB_GGCGACTGGATGCAG.fastq data/renamed/LRS_2735-076_RB.fastq
mv data/split/GTGAAA_RB_GGGCTCGGTATGCAG.fastq data/renamed/LRS_2735-077_RB.fastq
mv data/split/GTGAAA_RB_GGTGGAACAATGCAG.fastq data/renamed/LRS_2735-079_RB.fastq
mv data/split/GTGAAA_RB_GGAGCACCTCTGCAG.fastq data/renamed/LRS_2735-084_RB.fastq
mv data/split/GTGAAA_RB_GGCGACACACTGCAG.fastq data/renamed/LRS_2735-085_RB.fastq
mv data/split/GTGAAA_RB_GGCGCTGATCTGCAG.fastq data/renamed/LRS_2735-086_RB.fastq
mv data/split/GTGAAA_RB_GGACACAGAATGCAG.fastq data/renamed/LRS_2735-088_RB.fastq
mv data/split/GTGAAA_RB_GGCAACCACATGCAG.fastq data/renamed/LRS_2896-002_RB.fastq
mv data/split/GTGAAA_RB_GGCGCATACATGCAG.fastq data/renamed/LRS_2896-003_RB.fastq
mv data/split/GTGAAA_RB_GGGGAGAACATGCAG.fastq data/renamed/LRS_2896-004_RB.fastq
mv data/split/GTGAAA_RB_GGTGGCTTCATGCAG.fastq data/renamed/LRS_2896-006_RB.fastq
mv data/split/GTGAAA_RB_GGAGCCATGCTGCAG.fastq data/renamed/LRS_2896-007_RB.fastq
mv data/split/GTGAAA_RB_GGCGGATTGCTGCAG.fastq data/renamed/LRS_2896-008_RB.fastq
mv data/split/GTGAAA_RB_GGCAGATCTGTGCAG.fastq data/renamed/LRS_2896-010_RB.fastq
mv data/split/GTGAAA_RB_GGACAGCAGATGCAG.fastq data/renamed/LRS_2896-011_RB.fastq
mv data/split/GTGAAA_RB_GGCAAGACTATGCAG.fastq data/renamed/SNS_2894-072_RB.fastq
mv data/split/GTGAAA_RB_GGCTCAATGATGCAG.fastq data/renamed/SNS_2894-073_RB.fastq
mv data/split/GTGAAA_RB_GGGGTGCGAATGCAG.fastq data/renamed/SNS_2894-074_RB.fastq
mv data/split/GTGAAA_RB_GGTGGTGGTATGCAG.fastq data/renamed/SNS_2894-082_RB.fastq
mv data/split/GTGAAA_RB_GGAGGCTAACTGCAG.fastq data/renamed/SNS_2894-083_RB.fastq
mv data/split/GTGAAA_RB_GGCTAAGGTCTGCAG.fastq data/renamed/SNS_2894-084_RB.fastq
mv data/split/GTGAAA_RB_GGATGCCTAATGCAG.fastq data/renamed/SNS_2894-085_RB.fastq
mv data/split/GTGAAA_RB_GGACCTCCAATGCAG.fastq data/renamed/SNS_2894-086_RB.fastq
mv data/split/GTGAAA_RB_GGCAATGGAATGCAG.fastq data/renamed/SNS_2894-087_RB.fastq
mv data/split/GTGAAA_RB_GGCTGAGCCATGCAG.fastq data/renamed/SNS_2894-088_RB.fastq
mv data/split/GTGAAA_RB_GGGTACGCAATGCAG.fastq data/renamed/SNS_2894-089_RB.fastq
mv data/split/GTGAAA_RB_GGTTCACGCATGCAG.fastq data/renamed/SNS_2894-090_RB.fastq
mv data/split/GTGAAA_RB_GGATAGCGACTGCAG.fastq data/renamed/SNS_2894-091_RB.fastq
mv data/split/GTGAAA_RB_GGGAACAGGCTGCAG.fastq data/renamed/SNS_2894-092_RB.fastq
mv data/split/GTGAAA_RB_GGAACGAACGTGCAG.fastq data/renamed/SNS_2894-093_RB.fastq
mv data/split/GTGAAA_RB_GGACGCTCGATGCAG.fastq data/renamed/SNS_2894-094_RB.fastq
mv data/split/GTGAAA_RB_GGCACTTCGATGCAG.fastq data/renamed/SNS_2894-095_RB.fastq
mv data/split/GTGAAA_RB_GGCTGGCATATGCAG.fastq data/renamed/SNS_2894-096_RB.fastq
mv data/split/GTGAAA_RB_GGGTCGTAGATGCAG.fastq data/renamed/SNS_2898-077_RB.fastq
mv data/split/GTGAAA_RB_GGACACGAGATGCAG.fastq data/renamed/SNS_2898-084_RB.fastq
mv data/split/GTGAAA_RB_GGACGACAAGTGCAG.fastq data/renamed/SNS_2949_043_RB.fastq
mv data/split/GTGAAA_RB_GGGACAGTGCTGCAG.fastq data/renamed/SNS_2801-015_RB.fastq
mv data/split/GTGAAA_RB_GGAGTACAAGTGCAG.fastq data/renamed/SNS_2801-017_RB.fastq
mv data/split/GTGAAA_RB_GGACGTATCATGCAG.fastq data/renamed/SNS_2801-018_RB.fastq
mv data/split/GTGAAA_RB_GGCAGCGTTATGCAG.fastq data/renamed/SNS_2801-025_RB.fastq
mv data/split/GTGAAA_RB_GGGAATCTGATGCAG.fastq data/renamed/KSS_3734-001_RB.fastq
mv data/split/GTGAAA_RB_GGGTCTGTCATGCAG.fastq data/renamed/KSS_3734-002_RB.fastq
mv data/split/GTGAAA_RB_GGAAGAGATCTGCAG.fastq data/renamed/KSS_3734-003_RB.fastq
mv data/split/GTGAAA_RB_GGATTGGCTCTGCAG.fastq data/renamed/KSS_3734-004_RB.fastq
mv data/split/GTGAAA_RB_GGGAGTTAGCTGCAG.fastq data/renamed/KSS_3734-005_RB.fastq
mv data/split/GTGAAA_RB_GGCATCAAGTTGCAG.fastq data/renamed/KSS_3734-006_RB.fastq
mv data/split/GTGAAA_RB_GGACTATGCATGCAG.fastq data/renamed/KSS_3734-007_RB.fastq
mv data/split/GTGAAA_RB_GGCATACCAATGCAG.fastq data/renamed/KSS_3734-008_RB.fastq
mv data/split/GTGAAA_RB_GGGACTAGTATGCAG.fastq data/renamed/KSS_3734-009_RB.fastq
mv data/split/GTGAAA_RB_GGGTGTTCTATGCAG.fastq data/renamed/KSS_3734-010_RB.fastq
mv data/split/GTGAAA_RB_GGAAGGACACTGCAG.fastq data/renamed/KSS_3734-011_RB.fastq
mv data/split/GTGAAA_RB_GGCAAGGAGCTGCAG.fastq data/renamed/KSS_3734-012_RB.fastq
mv data/split/GTGAAA_RB_GGGATGAATCTGCAG.fastq data/renamed/KSS_3734-013_RB.fastq
mv data/split/GTGAAA_RB_GGAGTGGTCATGCAG.fastq data/renamed/KSS_3734-013_RB.fastq
mv data/split/GTGAAA_RB_GGAGAGTCAATGCAG.fastq data/renamed/KSS_3734-014_RB.fastq
mv data/split/GTGAAA_RB_GGCCAGTTCATGCAG.fastq data/renamed/KSS_3734-015_RB.fastq
mv data/split/GTGAAA_RB_GGGAGCTGAATGCAG.fastq data/renamed/KSS_3734-016_RB.fastq
