---
title: "700-wow-popgen"
author: "Mac Campbell"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
library(tidyverse)
library(viridis)
library(ggpubr)
library(grid)
library(gridExtra)
library(ggtree)
library(vcfR)
library(adegenet)
library(ape)
library(phangorn)
library(ggrepel)
```

## Looking at basic analyses of WOW


```{sh, eval=FALSE}
srun -p med -t 12:00:00 --mem=32G --nodes=2 $HOME/angsd/angsd -P 24  -bam bamlists/wow.bamlist \
-minInd 97 -GL 1 -ref $HOME/genomes/xyrauchen/Xyrauchen_texanus.faa \
-doGLF 2 -doMajorMinor 1 -doMaf 2 -SNP_pval 1e-6 -minMapQ 10 -minQ 20 -minMaf 0.05 \
-out outputs/700/wow > outputs/700/wow-beagle.out 2> outputs/700/wow-beagle.err &

python $HOME/pcangsd/pcangsd.py -beagle outputs/700/wow.beagle.gz -o outputs/700/wow-pca -threads 10
```


Generate some SNPs, 95% missing
```{sh, eval=FALSE}
srun -p med -t 24:00:00 --mem=16G --nodes=1 --ntasks=6 angsd -P 12 \
-bam bamlists/wow.bamlist \
-out /home/maccamp/wall-canyon/outputs/700/plink \
-anc $HOME/genomes/xyrauchen/Xyrauchen_texanus.faa \
-minInd 97 -minMaf 0.05  -minMapQ 10 -minQ 20 -GL 1 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doGeno 4 -doPost 1 -postCutoff 0.95 -doPlink 2 >outputs/700/std.out 2>outputs/700/std.err &
```


## PCA?

## Admixture

## DAPC

## Fst

