---
title: "802-wall-canyon-network"
author: "Mac Campbell"
date: "2023-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(ggtree)
library(tanggle)
library(phangorn)
library(ape)
```

```{r, warning=FALSE, message=FALSE}
source("~/github/SNPs2CF/functions.R")
```



```{r, warning=FALSE, message=FALE, eval=FALSE}
output <- SNPs2CF(seqMatrix="outputs/204/filtered.phy.varsites.phy",
                  ImapName="outputs/802/imap.txt", between.sp.only = TRUE, #max.SNPs = 1000,
                  n.quartets = 3,
                  bootstrap=FALSE, outputName="outputs/802/network-nq3-btsp.csv",
                  save.progress=FALSE,
                  cores = 3);
```

#Credibility Intervals
To bootstrap I need to put together CF's with CIs

```{r, warning=FALSE, message=FALE, eval=FALSE}
ciout <- SNPs2CF(seqMatrix="outputs/204/filtered.phy.varsites.phy",
                  ImapName="outputs/802/imap.txt", between.sp.only = TRUE, max.SNPs = NULL,
                  n.quartets = 3, bootstrap=TRUE, boots.rep=1000,
                  outputName="outputs/802/network-nq3-btsp-CI.csv",
                  save.progress=FALSE,
                  cores = 3);
```

# Starting Tree

tree.tre


# Implicit network
[1]  "Sacremento Sucker"        
 [4] "Modoc Sucker"              "
 [7] "        "Owens Sucker"             
[10] "Wall Canyon Sucker"        "Warner Sucker"            
```{r}
nm<-read_tsv("outputs/802/myfish2.tsv")  
nm$`Species Common Name`<-gsub("Sacremento","Sacramento",nm$`Species Common Name`)
nm$`Species Common Name`<-factor(nm$`Species Common Name`, 
                                 levels=c("Mountain Sucker","Tahoe Sucker",
                                         "Klamath Largescale Sucker","Klamath Smallscale Sucker",
                                         "Lost River Sucker","Shortnose Sucker",
                                         "Modoc Sucker","Sacramento Sucker",
                                         "Owens Sucker","Warner Sucker", "Wall Canyon Sucker"))
```

```{r}
net<-read.nexus.networx("outputs/204/splitstree.nex")
p <- ggsplitnet(net) 

p$data<-p$data %>% left_join(nm, by=c("label"="Sample ID"))
p
```

```{r}
p + geom_tippoint(aes(fill=`Species Common Name`), pch=21, cex=4, alpha=1) +
 # scale_fill_viridis_d(option="H") +
  scale_fill_manual(values=c("grey50","brown","grey50","grey50","grey50","grey50",
                             "purple","orange","red","blue","black"))

ggsave("outputs/802/splitstree.pdf")
```


```{r}
t1<-read.tree("outputs/802/net1.tre") 
t1<-root.phylo(t1, "MountainSucker")
ggevonet(as.evonet(t1)) + geom_tiplab() +
  xlim(0,20)
```

